### ISSUE TITLE
How to import ProcessOutCheckout3DS library

### ISSUE THREAD

**Issue by jeremierichard** [processout/processout-ios#126]
Hello 👋 ,

I'm integrating ProcessOut SDK `4.2.1` through Swift Package Manager and I'm not able to import `ProcessOutCheckout3DS` as it's not exposed as a product in your `Package.swift`.

Could you please add it?

Thanks.

**Comment by andrii-vysotskyi-cko** [comment]
Hey @jeremierichard, currently that is expected behaviour. I see that you opened an issue on [Checkout 3DS repository](https://github.com/checkout/checkout-3ds-sdk-ios/issues/29), probably we won't be able to move forward until it is resolved.

---

I thought that we could vendor copy of 3DS framework at least as a temporary solution but it won't work as well. Because it requires transitive dependency on [JOSESwift](https://github.com/airsidemobile/JOSESwift). It is an issue because 3DS framework links it dynamically but there is no dynamic product in SPM for JOSESwift.

**Comment by jeremierichard** [comment]
Thanks for your answer.
Indeed, I tried to do the same and ran into this same issue.
Now, let's hope Checkout 3DS will support SPM soon 🤞

**Comment by Fab1n** [comment]
> Hey @jeremierichard, currently that is expected behaviour. I see that you opened an issue on [Checkout 3DS repository](https://github.com/checkout/checkout-3ds-sdk-ios/issues/29), probably we won't be able to move forward until it is resolved.
> 
> I thought that we could vendor copy of 3DS framework at least as a temporary solution but it won't work as well. Because it requires transitive dependency on [JOSESwift](https://github.com/airsidemobile/JOSESwift). It is an issue because 3DS framework links it dynamically but there is no dynamic product in SPM for JOSESwift.

Hey @andrii-vysotskyi-cko here should be steps to resolve this issue:
- copy the `Checkout3DS*.xcframework`s
- copy `CheckoutEventLoggerKit.xcframework` as well (this is another dependency)
- compile [JOSESwift](https://github.com/airsidemobile/JOSESwift) with `BUILD_LIBRARY_FOR_DISTRIBUTION`
- create an XCFramework for `JOSESwift` and add it to the project

All these binaries need to be referenced inside the package description. 
I didn't try yet, but this could be a relatively simple thing to try if it works.
The one thing that is a bit more involved is the building and packaging of `JOSESwift`, but this could be also done within 1 hour.

What do you think?
It would be nice to give this a shot.

**Comment by andrii-vysotskyi-cko** [comment]
Hey @Fab1n, thank you for the suggestion. I see that there is a [PR](https://github.com/checkout/checkout-3ds-sdk-ios/pull/48) in Checkout repo doing what you are describing in regard to `JOSESwift` and hopefully it will be enough.

**Comment by andrii-vysotskyi-cko** [comment]
Hi @Fab1n, just to speed up the process we decided to temporarily vendor Checkout SDK to support SPM. It should be possible to use starting from `4.6.0`. Hopefully we will be able to replace it with proper dependency soon.

**Comment by Fab1n** [comment]
@andrii-vysotskyi-cko This is very good news, thanks for your work!!!
Let's see when Checkout3DS will be compliant.

**Comment by andrii-vysotskyi-cko** [comment]
Checkout3DS is now available via SPM so is `ProcessOutCheckout3DS` starting from `4.7.0` 🎉.

**Comment by jeremierichard** [comment]
Thanks @andrii-vysotskyi-cko !
