### ISSUE TITLE
After introducing CMark dependency we can not consume this framework as dynamic anymore

### ISSUE THREAD

**Issue by dcacenabes** [processout/processout-ios#140]
In version 4.1.0 a dependency with CMark was introduced.

https://github.com/processout/processout-ios/releases/tag/4.1.0

After bumping the process out dependency in our project we are getting the following error when compiling:

```[!] The 'Pods-XX' target has transitive dependencies that include statically linked binaries: (/Users/x/xx_develop/Pods/ProcessOut/Vendor/cmark.xcframework)```

Is there any way to keep using the library as a dynamic framework?

**Comment by dcacenabes** [comment]
Hey @andrii-vysotskyi-cko ,
Thanks for addressing this so promptly!
Should we expect a new release anytime soon? We're considering pointing to the main branch or waiting for a new released to be published.

**Comment by andrii-vysotskyi-cko** [comment]
Hi @dcacenabes, dynamic framework will be more flexible so thanks for reporting! Release jobs are already running so will be available soon in `4.4.0`. Usually it takes ~30 min to push podspecs, progress is available [here](https://github.com/processout/processout-ios/actions/runs/5600787664).

**Comment by dcacenabes** [comment]
Thanks a bunch! If the jobs are running already we'll most likely wait :) Have a good day!
