### ISSUE TITLE
POAssignCustomerTokenRequest tokenId

### ISSUE THREAD

**Issue by sergey-shablenko** [processout/processout-ios#256]
Hi, could you explain where do I get tokenId for POAssignCustomerTokenRequest?
I cannot find anything like that in [api reference](https://docs.processout.com/reference/creating-a-token), it only takes customerId and sourceId, there is no tokenId
How do I generate it or where do I get it from?

**Comment by andrii-vysotskyi-cko** [comment]
Hi @sergey-shablenko , sure.

You need to create token using [this](https://docs.processout.com/reference/creating-a-token) method (it should be called from your backend, where private key is stored). In response token object there is an `id` that should be set as `tokenId` when creating `POAssignCustomerTokenRequest `.

Please also check [this](https://docs.processout.com/docs/saving-a-token-to-capture-future-payments) documentation on how to create tokens.

**Comment by sergey-shablenko** [comment]
what does this method do then?
tokenizeCard creates source token
tokenId is created on backed, which already requires source, so token will already contain source
what is the purpose of this method?

**Comment by andrii-vysotskyi-cko** [comment]
> tokenId is created on backed, which already requires source, so token will already contain source

It is not necessary to pass source when creating token 

Purpose of this method is to assign source to "empty" token and have verified if needed.
