### ISSUE TITLE
Building failure with Xcode 16

### ISSUE THREAD

**Issue by albsala-backmarket** [processout/processout-ios#336]
Hi there, we're preparing to be ready for adopting iOS 18 and Xcode 16, that are supposed to be released in a month, but ProcessOutCheckout3DS is failing on building the project.
I'm using Xcode 16 beta 6 (last beta as for Today).

This is the error:

> Failed to build module 'Checkout3DS'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)', while this compiler is 'Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)'). Please select a toolchain which matches the SDK.

<img width="796" alt="Screenshot 2024-08-22 at 15 48 58" src="https://github.com/user-attachments/assets/5a1a65f3-aacf-47f6-b553-fad7c8977297">

**Comment by andrii-vysotskyi-cko** [comment]
Hey @albsala-backmarket , apologies for inconvenience. CKO team is already aware and working on fix

**Comment by albsala-backmarket** [comment]
Hi @andrii-vysotskyi-cko, any update about this topic? Do we have any ETC?
Thank you

**Comment by Armay2** [comment]
Hi @andrii-vysotskyi-cko, 
Any news? It's impossible to upgrade to **Xcode 16** without your dev 
Thank you

**Comment by andrii-vysotskyi-cko** [comment]
Hi, Checkout team recently released updated version with support of Xcode 16. We are currently [testing](https://github.com/processout/processout-ios/pull/375) it, and will merge as soon as ready.

**Comment by andrii-vysotskyi-cko** [comment]
Should be fixed in [4.22.0](https://github.com/processout/processout-ios/releases/tag/4.22.0).
