### ISSUE TITLE
Example project does not open because it is missing its project.pbxproj file

### ISSUE THREAD

**Issue by yusufkamilak** [processout/processout-ios#372]
Hey, I was trying to check out the example project to see an example application of ProcessOutUI. Even though I cloned the repo and then followed the instructions at read.me file, I am unable to initiate the project as pbxproj file doesn't seem to be generated. Here's what I did:

> Before going further please make sure that you have installed all dependencies specified in [requirements](https://github.com/processout/processout-ios/issues/new#development-requirements) section. Then in order to install remaining dependencies and prepare a project run ./Scripts/BootstrapProject.sh script from repository's root directory. It will create ProcessOut.xcodeproj project that should be used for development.

The problem I face is as below:
<img width="940" alt="Screenshot 2024-10-22 at 13 57 06" src="https://github.com/user-attachments/assets/31d45411-e6f5-407d-a40c-2b49b383e47c">

When I try `Show Package Contents` on `Example.xcodeproj`, I see a `.workspace` file, which also does not open. But frankly there is no `.pbxproj` file inside. So I'm wondering if anything's wrong with the script (even though logs didn't indicate any issues when I ran the script as instructed).

As this is part of an effort towards integrating ProcessOut into our products, I would appreciate any rapid support on this. Thank you!

**Comment by andrii-vysotskyi-cko** [comment]
Hi @yusufkamilak , could you please confirm that you went through setup described in [README](https://github.com/processout/processout-ios/tree/master/Example) of Example's project and not repo's root?

**Comment by yusufkamilak** [comment]
Hey @andrii-vysotskyi-cko , yes I followed this setup, however in 2nd step `Example.xcodeproj` won't open with the error I shared the screenshot above. When I check encapsulated files, I don't see a `.pbxproj` file inside as well. I can confirm that I tried both with Xcode 15.4 and Xcode 16, I have a valid homebrew setup and I tried opening after running the script as instructed. 

NOTE: The main project `ProcessOut.xcodeproj` works btw. I try to run `/Users/yusuf.kamilak/Projects/ProcessOut/Example/Example.xcodeproj`

**Comment by yusufkamilak** [comment]
It's crazy but I restarted the Mac and tried again now, even though I received the same output from script as below, now it seems to be working 🤦 
```
Homebrew Bundle complete! 5 Brewfile dependencies now installed.
⚙️  Generating plists...
⚙️  Generating project...
⚙️  Writing project...
Created project at /Users/yusuf.kamilak/Projects/ProcessOut/ProcessOut.xcodeproj
```

Closing the issue as it seems to be resolved right now

**Comment by andrii-vysotskyi-cko** [comment]
I suspect you may be running the script from project's root, that's why `ProcessOut.xcodeproj` is generated but `Example.xcodeproj` is not. 

Could you execute it while being in Example folder ?

**Comment by yusufkamilak** [comment]
hmm, yeah this solved the issue. Maybe it'd be worth updating the instructions as:
`cd Example`
`sh ../Scripts/BootstrapProject.sh`
Thanks for the support!
